language: r
cache: packages
sudo: false
cran: http://cran.rstudio.com

r:
  - 3.2
  - oldrel
  - release
  - devel

addons:
  apt:
    packages:
      - libv8-dev
      - librsvg2-dev
      - graphviz

after_success:
  - Rscript -e 'covr::coveralls()'
